services:
  cowallet:
    image: ghcr.io/ninidas/cowallet:latest
    container_name: cowallet
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PUID=1000
      - PGID=1000
      - APP_LANG=en  # Default language for seeded data: en or fr
      # - MAX_GROUPS=1  # Max number of couples allowed (default: 1, set higher to allow more)
    volumes:
      - <host_folder_data>:/data
