services:
  cowallet-frontend:
    image: ghcr.io/ninidas/cowallet-frontend:latest
    container_name: cowallet-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - cowallet-backend

  cowallet-backend:
    image: ghcr.io/ninidas/cowallet-backend:latest
    container_name: cowallet-backend
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - APP_LANG=en  # Default language for seeded data: en or fr
    volumes:
      - <host_folder_data>:/data
